### PR TITLE
update incorrect pinecone quick start pathname

### PR DESCRIPTION
**Pull request by abpai**
## Problem

Describe the purpose of this change. What problem is being solved and why?

The quick start link reference in the debug output led to a 404 page

## Solution

Found the right page, _I think_:  https://docs.pinecone.io/docs/quickstart

## Type of Change

- [] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [x] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

Run canopy command without specifying the environment variable.

### CODE REVIEW

**Review by miararoy — APPROVED** [review]
Lgtm

**Comment by miararoy** [comment]
@igiloh-pinecone waiting your approval, and ci clearance

**Comment by igiloh-pinecone** [comment]
> @igiloh-pinecone waiting your approval, and ci clearance

The fact that we need to approve every CI run is not intentional. The "heavier" CI jobs that require secrets access are anyway configured to run only in the merge queue, after a PR has been approved.  
I'll fix it

**Review by igiloh-pinecone — APPROVED** [review]
LGTM!

Thanks @abpai for your contribution

**Pull request merged**
